- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/red_cube/pose"
  gz_topic_name: "/model/red_cube/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS

- ros_topic_name: "/model/blue_cube/pose"
  gz_topic_name: "/model/blue_cube/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "gz.msgs.Pose"
  direction: GZ_TO_ROS